<?php

use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * @file
 * Contains content_lister.module.
 */

function get_nodes($opt, $type) {
  $res = array();
  $db = \Drupal::database();
  if($opt == "All") {
    $results = $db->select('node')
      ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
      ->limit(50);
    $results->fields('node');
    $results->orderBy('nid','ASC');
    $res = $results->execute()->fetchAll();
    $ret = [];
  } else {
    $results = $db->select('node')
      ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
      ->limit(50);
    $results->fields('node');
    $results->orderBy('nid','ASC');
    $results->condition('type', $type);
    $res = $results->execute()->fetchAll();
    $ret = [];
  }
  foreach ($res as $row) {
    $delete = Url::fromUserInput('/admin/structure/content_lister/nodes/delete/' . $row->nid, array('attributes' => array('onclick' => "return confirm('Are you Sure')")));
    $edit = Url::fromUserInput('/admin/structure/content_lister/nodes/edit/' . $row->nid);

    $edit_link = Link::fromTextAndUrl('edit', $edit)->toString();
    $delete_link = Link::fromTextAndUrl('delete', $delete)->toString();

    $mainLink = t('@linkApprove  @linkReject', array('@linkApprove' => $edit_link, '@linkReject' => $delete_link));

    $ret[] = [
      'nid' => $row->nid,
      'vid' => $row->vid,
      'type' => $row->type,
      'uuid' => $row->uuid,
      'langcode' => $row->langcode,
      'opt' => $mainLink,
    ];
  }
  return $ret;
}

function get_nodes_field_data($opt, $type, $title) {
  $res = array();
  $db = \Drupal::database();
  if($opt == "All") {
    $results = $db->select('node_field_data')
      ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
      ->limit(25);
    $results->fields('node_field_data');
    $results->orderBy('nid','ASC');
    $results->condition('type', $type);
    $res = $results->execute()->fetchAll();
    $ret = [];
  } else {
    $results = $db->select('node_field_data')
      ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
      ->limit(25);
    $results->fields('node_field_data');
    $results->orderBy('nid','ASC');
    $results->condition('type', $type);
    $results->condition('title', $title);
    $res = $results->execute()->fetchAll();
    $ret = [];
  }
  foreach ($res as $row) {
    $delete = Url::fromUserInput('/admin/structure/content_lister/nodes/delete/' . $row->nid, array('attributes' => array('onclick' => "return confirm('Are you Sure')")));
    $edit = Url::fromUserInput('/admin/structure/content_lister/nodes/edit/' . $row->nid);
    $edit_link = Link::fromTextAndUrl('edit', $edit)->toString();
    $delete_link = Link::fromTextAndUrl('delete', $delete)->toString();
    $mainLink = t('@linkApprove  @linkReject', array('@linkApprove' => $edit_link, '@linkReject' => $delete_link));
    $title_url_text = Url::fromUserInput('/node/' . $row->nid);
    $title_link = Link::fromTextAndUrl($row->title, $title_url_text)->toString();
    $title_uri = t('@linkApprove', array('@linkApprove' => $title_link));
    $ret[] = [
      'nid' => $row->nid,
      'vid' => $row->vid,
      'type' => $row->type,
      'title' => $title_uri,
      'opt' => $mainLink,
    ];
  }
  return $ret;
}
