<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_entity_insert().
 */
function new_custom_queue_entity_insert(EntityInterface $entity) {
  if ($entity->bundle() === 'event') {
    /** @var QueueInterface $queue */
    $queue = \Drupal::service('queue')->get('headlines_queue');
    $queue->createItem($entity);
  }
}

/**
 * Implements hook_schema().
 */
function new_custom_module_schema() {
  $schema['organizer_headlines'] = [
    'description' => 'Organizer Headline',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'headline' => [
        'type' => 'varchar',
        'not null' => TRUE,
        'length' => 255,
        'default' => '',
      ],
    ],
    'primary key' => ['id'],
  ];
//  $schema = \Drupal\Core\Database\Database::getConnection()->schema();
//  $schema->createTable('organizer_headlines', $spec);
  return $schema;
}
