<?php

/**
 * Implementation of hook_init().
 */
function site_status_message_init() {
  $enabled = \Drupal::state()->get('site_status_message_enabled', FALSE);
  $type = \Drupal::state()->get('site_status_message_type', 'status');
  $text = \Drupal::state()->get('site_status_message_text', '');
  if ($enabled && $text) {
    \Drupal::messenger()->addStatus($text, $type);
  }
}

/**
 * Implementation of hook_menu().
 */
function site_status_message_menu() {
  $items['admin/config/system/status/site_status_message'] = array(
    'title' => t('Status message'),
    'description' => t('Set a Drupal message.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_status_message_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Admin settings form
 */
function site_status_message_settings() {
  $form['site_status_message_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show message.'),
    '#description' => t('Enable the message.'),
    '#default_value' => \Drupal::state()->get('site_status_message_enabled', FALSE),
  );
  $form['site_status_message_type'] = array(
    '#type' => 'select',
    '#title' => t('Message type'),
    '#options' => array(
      'status' => t('Status'),
      'error' => t('Error'),
      'warning' => t('Warning'),
    ),
    '#default_value' => \Drupal::state()->get('site_status_message_type', 'status'),
  );
  $form['site_status_message_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Message to show.'),
    '#default_value' => \Drupal::state()->get('site_status_message_text',''),
    '#size' => 100,
  );
  return  \Drupal\Core\Form\ConfigFormBase($form);
}

