<?php

/**
 * @file
 * Provides a review entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function review_theme() {
  return [
    'review' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for review templates.
 *
 * Default template: review.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the review information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_review(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function review_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish reviews.
      $storage = \Drupal::entityTypeManager()->getStorage('review');
      $review_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($review_ids) as $review) {
        $review->set('status', FALSE);
        $review->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize reviews.
      $storage = \Drupal::entityTypeManager()->getStorage('review');
      $review_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($review_ids) as $review) {
        $review->setOwnerId(0);
        $review->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function review_user_predelete(UserInterface $account) {
  // Delete reviews.
  $storage = \Drupal::entityTypeManager()->getStorage('review');
  $review_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $reviews = $storage->loadMultiple($review_ids);
  $storage->delete($reviews);
}
