<?php

use Drupal\taxonomy\TermInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_cron().
 */
function search_api_field_cron() {
  search_api_cron();
  $query = \Drupal::entityQuery('node');
  $nids = $query->execute();
  $nodes = Node::loadMultiple($nids);
  foreach ($nodes as $node) {
    $node->set("title", strtoupper($node->title->value));
    $node->save();
  }
  $node_company = Node::create([
    'type' => 'company',
    'langcode' => 'en',  
  ]);  
} 

function search_api_field_entity_presave(EntityInterface $entity) {
  if ($entity instanceof TermInterface) {
    if ($entity->bundle() == 'companies') {
      search_api_entity_update($entity);
    }
  }
}