<?php

/**
 * Implements hook_entity_presave().
 */
function event_title_entity_presave($entity) {
  switch ($entity->bundle()) {
    case 'event':
      $casedTitle = \Drupal::service('event_title.custom_services')->titleCase($entity);
      $entity->setTitle($casedTitle);
      break;
  }
}

/**
 * Implements hook_post_update_NAME().
 *
 * @param $sandbox
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function event_title_post_update_name(&$sandbox) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $nid = $node->id();
  }
  $node = \Drupal\node\Entity\Node::load($nid);
  $casedTitle = \Drupal::service('event_title.custom_services')->titleCase($node);
  $node->setTitle($casedTitle);
  $node->save();
  $result = t('Node %nid saved', [
    '%nid' => $node->id(),
  ]);
  return $result;
}
