<?php

/**
 * @file
 * Provides a content entity drushgen entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\content_entity_drushgen\Entity\ContentEntityDrushgen;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function content_entity_drushgen_theme() {
  return [
    'content_entity_drushgen' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for content entity drushgen templates.
 *
 * Default template: content-entity-drushgen.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content entity drushgen information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_entity_drushgen(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function content_entity_drushgen_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish content entity drushgens.
      $storage = \Drupal::entityTypeManager()->getStorage('content_entity_drushgen');
      $content_entity_drushgen_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($content_entity_drushgen_ids) as $content_entity_drushgen) {
        $content_entity_drushgen->set('status', FALSE);
        $content_entity_drushgen->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize content entity drushgens.
      $storage = \Drupal::entityTypeManager()->getStorage('content_entity_drushgen');
      $content_entity_drushgen_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($content_entity_drushgen_ids) as $content_entity_drushgen) {
        $content_entity_drushgen->setOwnerId(0);
        $content_entity_drushgen->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function content_entity_drushgen_user_predelete(UserInterface $account) {
  // Delete content entity drushgens.
  $storage = \Drupal::entityTypeManager()->getStorage('content_entity_drushgen');
  $content_entity_drushgen_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $content_entity_drushgens = $storage->loadMultiple($content_entity_drushgen_ids);
  $storage->delete($content_entity_drushgens);
}
