<?php

/**
 * @file
 * Holds hook implementation for the Message example module.
 */

use Drupal\node\Entity\Node;
use Drupal\message\Entity\Message;

/**
 * Implements hook_node_insert().
 */
function notification1_node_insert(Node $node) {
  if ($node->getType() === 'event') {
    $message = Message::create(['template' => 'event_created', 'uid' => $node->get('uid')]);
    $message->set('field_node_reference', $node);
    if($node->get('field_event_type')->getValue() != []) {
      $eventType = $node->get('field_event_type')->getValue()[0]['target_id'];
      $message->set('field_event_type_message', $eventType);
      $text = $message->getText()[0];
      $html = \Drupal::token()->replace($text, [
        'node' => $node,
      ], []);
      $html = strip_tags(html_entity_decode($html));
      $message->set('field_message_show', str_replace('&nbsp;', ' ', $html));
      $message->save();
    }
  }
}

/**
 * Implements hook_theme().
 */
function notification1_theme() {
  return [
    'notification1' => [
      'variables' => [
        'content' => NULL
      ],
    ],
  ];
}

function notification1_views_query_alter(
  \Drupal\views\ViewExecutable $view,
  \Drupal\views\Plugin\views\query\QueryPluginBase $query){
  if($view->id() == 'notifications2'){
    $userId = \Drupal::currentUser()->id();
    if ($userId) {
      $user = \Drupal::entityTypeManager()->getStorage('user')->load($userId);
      $limit = $user->get('field_maximum_notifications')->getValue()[0]['value'];
      $view->getPager()->setItemsPerPage($limit);
    }
  }
}
