<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

///**
// * Implements hook_entity_view_alter().
// */
//function organizer_news_queue_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
//  if ($build['#view_mode'] == 'full' && isset($build['field_event_organizer'])) {
//    dd($entity->get('field_event_organizer')->getValue()[0]['target_id']);
//  }
//}

/**
 * Implements hook_entity_insert().
 */
function organizer_news_queue_entity_insert(EntityInterface $entity) {
  if($entity->getEntityType() !== 'node') {

  }

  if($entity->isPublished()){

  }

  /**   @var QueueFactory $queue_factory   */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('cron_node_publisher');
  $item = new \stdClass();
  $item->nid = $entity->id();
  $queue->createItem($item);
}
