<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view_alter().
 */
function organizer_news_queue_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($build['#view_mode'] == 'full' && isset($build['field_event_organizer'])) {
    dd($entity->get('field_event_organizer')->getValue()[0]['target_id']);
//    dd($entity->get('type')->getValue()[0]['target_id']);
  }
}
